use_frameworks!

platform :ios, '8.0'

target 'XYXLNetworking_Example' do
  pod 'XYXLNetworking', :path => '../'

  target 'XYXLNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
